
SET NAMES utf8mb4;

INSERT INTO object_localized_query_16_en_GB (`ooo_id`,`language`,`icon`,`name`,`seoname`,`description`,`link`,`images`,`documents`,`videos`,`downloads`) VALUES ('104','en_GB',NULL,'Stretch Woven','Stretch Woven',NULL,'N;',NULL,NULL,NULL,NULL);
INSERT INTO object_localized_query_16_en_GB (`ooo_id`,`language`,`icon`,`name`,`seoname`,`description`,`link`,`images`,`documents`,`videos`,`downloads`) VALUES ('121','en_GB',NULL,'Windstopper Fabric','Windstopper Fabric',NULL,'N;',NULL,NULL,NULL,NULL);
INSERT INTO object_localized_query_16_en_GB (`ooo_id`,`language`,`icon`,`name`,`seoname`,`description`,`link`,`images`,`documents`,`videos`,`downloads`) VALUES ('125','en_GB',NULL,'Woven','Woven',NULL,'N;',NULL,NULL,NULL,NULL);
INSERT INTO object_localized_query_16_en_GB (`ooo_id`,`language`,`icon`,`name`,`seoname`,`description`,`link`,`images`,`documents`,`videos`,`downloads`) VALUES ('132','en_GB',NULL,'PU','PU',NULL,'N;',NULL,NULL,NULL,NULL);
INSERT INTO object_localized_query_16_en_GB (`ooo_id`,`language`,`icon`,`name`,`seoname`,`description`,`link`,`images`,`documents`,`videos`,`downloads`) VALUES ('134','en_GB',NULL,'Cotton Jersey','Cotton Jersey',NULL,'N;',NULL,NULL,NULL,NULL);
INSERT INTO object_localized_query_16_en_GB (`ooo_id`,`language`,`icon`,`name`,`seoname`,`description`,`link`,`images`,`documents`,`videos`,`downloads`) VALUES ('136','en_GB',NULL,'Canvas','Canvas',NULL,'N;',NULL,NULL,NULL,NULL);
INSERT INTO object_localized_query_16_en_GB (`ooo_id`,`language`,`icon`,`name`,`seoname`,`description`,`link`,`images`,`documents`,`videos`,`downloads`) VALUES ('140','en_GB',NULL,'Mesh','Mesh',NULL,'N;',NULL,NULL,NULL,NULL);
INSERT INTO object_localized_query_16_en_GB (`ooo_id`,`language`,`icon`,`name`,`seoname`,`description`,`link`,`images`,`documents`,`videos`,`downloads`) VALUES ('141','en_GB',NULL,'Elasthan','Elasthan',NULL,'N;',NULL,NULL,NULL,NULL);
INSERT INTO object_localized_query_16_en_GB (`ooo_id`,`language`,`icon`,`name`,`seoname`,`description`,`link`,`images`,`documents`,`videos`,`downloads`) VALUES ('144','en_GB',NULL,'Synthetic','Synthetic',NULL,'N;',NULL,NULL,NULL,NULL);
INSERT INTO object_localized_query_16_en_GB (`ooo_id`,`language`,`icon`,`name`,`seoname`,`description`,`link`,`images`,`documents`,`videos`,`downloads`) VALUES ('148','en_GB',NULL,'Synthetic Leather','Synthetic Leather',NULL,'N;',NULL,NULL,NULL,NULL);
INSERT INTO object_localized_query_16_en_GB (`ooo_id`,`language`,`icon`,`name`,`seoname`,`description`,`link`,`images`,`documents`,`videos`,`downloads`) VALUES ('149','en_GB',NULL,'Mesh Fabrics','Mesh Fabrics',NULL,'N;',NULL,NULL,NULL,NULL);
INSERT INTO object_localized_query_16_en_GB (`ooo_id`,`language`,`icon`,`name`,`seoname`,`description`,`link`,`images`,`documents`,`videos`,`downloads`) VALUES ('151','en_GB',NULL,'Phylon / TPR','Phylon / TPR',NULL,'N;',NULL,NULL,NULL,NULL);
INSERT INTO object_localized_query_16_en_GB (`ooo_id`,`language`,`icon`,`name`,`seoname`,`description`,`link`,`images`,`documents`,`videos`,`downloads`) VALUES ('153','en_GB',NULL,'Nylon','Nylon',NULL,'N;',NULL,NULL,NULL,NULL);
INSERT INTO object_localized_query_16_en_GB (`ooo_id`,`language`,`icon`,`name`,`seoname`,`description`,`link`,`images`,`documents`,`videos`,`downloads`) VALUES ('159','en_GB',NULL,'PES Woven Peach','PES Woven Peach',NULL,'N;',NULL,NULL,NULL,NULL);
INSERT INTO object_localized_query_16_en_GB (`ooo_id`,`language`,`icon`,`name`,`seoname`,`description`,`link`,`images`,`documents`,`videos`,`downloads`) VALUES ('161','en_GB',NULL,'Phylon','Phylon',NULL,'N;',NULL,NULL,NULL,NULL);
INSERT INTO object_localized_query_16_en_GB (`ooo_id`,`language`,`icon`,`name`,`seoname`,`description`,`link`,`images`,`documents`,`videos`,`downloads`) VALUES ('163','en_GB',NULL,'Polyamide','Polyamide',NULL,'N;',NULL,NULL,NULL,NULL);
INSERT INTO object_localized_query_16_en_GB (`ooo_id`,`language`,`icon`,`name`,`seoname`,`description`,`link`,`images`,`documents`,`videos`,`downloads`) VALUES ('166','en_GB',NULL,'Rubber','Rubber',NULL,'N;',NULL,NULL,NULL,NULL);
INSERT INTO object_localized_query_16_en_GB (`ooo_id`,`language`,`icon`,`name`,`seoname`,`description`,`link`,`images`,`documents`,`videos`,`downloads`) VALUES ('168','en_GB',NULL,'Polyester','Polyester',NULL,'N;',NULL,NULL,NULL,NULL);
INSERT INTO object_localized_query_16_en_GB (`ooo_id`,`language`,`icon`,`name`,`seoname`,`description`,`link`,`images`,`documents`,`videos`,`downloads`) VALUES ('171','en_GB',NULL,'TPR','TPR',NULL,'N;',NULL,NULL,NULL,NULL);
INSERT INTO object_localized_query_16_en_GB (`ooo_id`,`language`,`icon`,`name`,`seoname`,`description`,`link`,`images`,`documents`,`videos`,`downloads`) VALUES ('180','en_GB',NULL,'EVA  / Rubber','EVA  / Rubber',NULL,'N;',NULL,NULL,NULL,NULL);
INSERT INTO object_localized_query_16_en_GB (`ooo_id`,`language`,`icon`,`name`,`seoname`,`description`,`link`,`images`,`documents`,`videos`,`downloads`) VALUES ('181','en_GB',NULL,'Spandex','Spandex',NULL,'N;',NULL,NULL,NULL,NULL);
INSERT INTO object_localized_query_16_en_GB (`ooo_id`,`language`,`icon`,`name`,`seoname`,`description`,`link`,`images`,`documents`,`videos`,`downloads`) VALUES ('185','en_GB',NULL,'Phylon / Rubber','Phylon / Rubber',NULL,'N;',NULL,NULL,NULL,NULL);
INSERT INTO object_localized_query_16_en_GB (`ooo_id`,`language`,`icon`,`name`,`seoname`,`description`,`link`,`images`,`documents`,`videos`,`downloads`) VALUES ('934','en_GB',NULL,'TPU','TPU',NULL,'N;',NULL,NULL,NULL,NULL);
